kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-backup
  labels:
    app: kube-backup
    env: system
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-backup
  labels:
    app: kube-backup
    env: system
subjects:
  - kind: ServiceAccount
    namespace: kube-backup
    name: default
  - kind: User
    name: kube-backup
roleRef:
  kind: ClusterRole
  name: kube-backup
  apiGroup: rbac.authorization.k8s.io
